name: culinara
description: "Unlock your culinary creativity with Culinara! Discover unique ingredient combinations, explore innovative recipes, and share your delicious creations with a vibrant community. Whether you're a home cook seeking fresh inspiration or looking to experiment with new flavors, Culinara makes every meal an exciting adventure."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.1
  # dart run easy_localization:generate -S "assets/translations" -f keys -o "locale_keys.g.dart"  
  flex_color_scheme: ^7.3.1
  easy_localization: ^3.0.5 

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
